### PR TITLE
Upgraded substrate version to 2.0.1

### PR DESCRIPTION
**Pull request by maxsam4**

### CODE REVIEW

**Comment by aafshar-poly** [comment]
@maxsam4 depending on the changes in Polymesh, you might want to cherry-pick this to `v1-mainnet` branch as well.

**Review by vkomenda — APPROVED** [review]

**Comment by maxsam4** [comment]
@ParnianAlimi @aafshar-poly Why is the git diff so large?

**Comment by ParnianAlimi** [comment]
> @ParnianAlimi @aafshar-poly Why is the git diff so large?

I rebased it on the latest `develop` -- there were some merge conflicts. the PR pulls in the commits, but when we merge this to develop it will only add your changes.

**Comment by vkomenda** [comment]
@Parnian, the rebased version was indeed not clean. I've cherry-picked the commit by @maxsam4 on top of develop and now the diff contains just that commit.

**Pull request closed without merging**
